#!/usr/bin/env bash

parentdir="$(dirname "$(pwd)")"

jqf="$parentdir/JQF"

sed -i -e 's/\r$//' $(pwd)/scripts/*
sed -i -e 's/\r$//' $jqf/bin/*
sed -i -e 's/\r$//' $jqf/scripts/*
sed -i -e 's/\r$//' $jqf/scripts/experiments/ei/*
sed -i -e 's/\r$//' $jqf/scripts/experiments/ei/data-processing/*
sed -i -e 's/\r$//' $jqf/scripts/experiments/zest/*
