#!/bin/bash

if [ $# -lt 2 ]; then
  echo "Usage: $0 ID-FROM ID-TO" 2>/dev/null
  exit 1
fi

id1=$1
id2=$2
time=$((1*60*60))
timeouts=$((time + 30))

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

for id in $(seq $id1 $id2); do

  echo "semantic-zest-$id timeout ${timeouts}s "
  screen -S "semantic-zest-$id" -dm -t "semantic-zest-$id"
  screen -S "semantic-zest-$id" -p "semantic-zest-$id" -X stuff "timeout ${timeouts}s $SCRIPT_DIR/run_jqf \"semantic-zest\" $id ^M"
#    sleep $time
 #   sleep 10
  #$SCRIPT_DIR/run_jqf "semantic-zest" $id

  echo "syntactic-zest-$id timeout ${timeouts}s"
  screen -S "syntactic-zest-$id" -dm -t "syntactic-zest-$id"
  screen -S "syntactic-zest-$id" -p "syntactic-zest-$id" -X stuff "timeout ${timeouts}s $SCRIPT_DIR/run_jqf \"syntactic-zest\" $id -b ^M"
  # sleep $time
  # sleep 10
  #$SCRIPT_DIR/run_jqf "syntactic-zest" $id -b

  echo "semantic-noguidance-$id timeout ${timeouts}s"
  screen -S "semantic-noguidance-$id" -dm -t "semantic-noguidance-$id"
  screen -S "semantic-noguidance-$id" -p "semantic-noguidance-$id" -X stuff "timeout ${timeouts}s $SCRIPT_DIR/run_jqf \"semantic-noguidance\" $id ^M"
   #sleep $time
   #sleep 10
    #$SCRIPT_DIR/run_jqf "semantic-noguidance" $id

  echo "syntactic-noguidance-$id timeout ${timeouts}s"
  screen -S "syntactic-noguidance-$id" -dm -t "syntactic-noguidance-$id"
  screen -S "syntactic-noguidance-$id" -p "syntactic-noguidance-$id" -X stuff "timeout ${timeouts}s $SCRIPT_DIR/run_jqf \"syntactic-noguidance\" $id -b ^M"

  #SCRIPT_DIR/run_jqf "syntactic-noguidance" $id -b

  sleep $time
  sleep 10

done
