#!/usr/bin/env bash


#-k -> keeptestfiles
#-g -> guidance ei or zest
#-b -> basic generator

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

$SCRIPT_DIR/run_jqf_all $@
$SCRIPT_DIR/run_repro_all $@
