#!/usr/bin/env bash

#blind
export JVM_OPTS="$JVM_OPTS -Djqf.ei.TOTALLY_RANDOM=true"

#-k -> keeptestfiles
#-g -> guidance ei or zest
#-b -> basic generator


/usr/bin/env bash -c "./scripts/run_jqf $@"
