#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

parentdir="$(dirname "$SCRIPT_DIR")"
sourcedir="$(dirname "$parentdir")"

DRIVER_PATH="$sourcedir/JQF/scripts/jqf-driver.sh"
JAR_PATH="$parentdir/build/libs/growe-1.0-SNAPSHOT-all.jar"

LOGFILE="./executor.log"

function log() {
  echo "$1" | tee -a "$LOGFILE"
}

DURATIONHOURS=1
#DURATIONSECONDS=$((2 * 60))
DURATIONSECONDS=$((DURATIONHOURS * 60 * 60 ))
ITERATIONS=0 # 0 == no limit

print_usage() {
  echo "Usage: $0 NAME ITERATION other(jqf), got $*"
}

# Check arguments
if [ $# -lt 2 ]; then
  print_usage >&1
  exit 1
fi


EXEC_DIR="nextflow-$1-$2"

export JVM_OPTS="$JVM_OPTS -Djqf.ei.MAX_INPUT_SIZE=100000000" #byte #1000000 == 1MB
export JVM_OPTS="$JVM_OPTS -Djqf.logCoverage=true"
export JVM_OPTS="$JVM_OPTS -Djqf.ei.QUIET_MODE=false"
export JVM_OPTS="$JVM_OPTS -DuseFastNonCollidingCoverageInstrumentation=true"

# Do not let GC mess with fuzzing
export JVM_OPTS="$JVM_OPTS -XX:-UseGCOverheadLimit -Djqf.tracing.MATCH_CALLEE_NAMES=true"


#ei guidance
#export JVM_OPTS="$JVM_OPTS -Djqf.tracing.TRACE_GENERATORS=true"

#debug
if [[ $* == *"debug"* ]]; then
  export JVM_OPTS="$JVM_OPTS -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005"
fi
function executeTest() {

  #core execution
  log ""
  log "===== Executing  ====="

  #-k -> keeptestfiles
  #-g -> guidance ei or zest
  #-b basic generator

  if [[ $1 == *"noguidance"* ]]; then
    export JVM_OPTS="$JVM_OPTS -Djqf.ei.TOTALLY_RANDOM=true -Djqf.ei.DISABLE_SAVE_NEW_COUNTS=true"
    /usr/bin/env bash -c "JVM_OPTS=$OPTS $DRIVER_PATH --illegal-access=permit -Xmx6G -jar $JAR_PATH -d $DURATIONSECONDS -i $ITERATIONS ${*: 3} | tee -a $LOGFILE 2>/dev/null"
  else
    /usr/bin/env bash -c "$DRIVER_PATH --illegal-access=permit -Xmx6G -jar $JAR_PATH -d $DURATIONSECONDS -i $ITERATIONS ${*: 3} | tee -a $LOGFILE 2>/dev/null"
  fi

}

# execution preparation
mkdir -p "$EXEC_DIR" || return 1
cd "$EXEC_DIR" || return 1

executeTest "$@"

rm -r work/
rm -r .nextflow/
rm .nextflow.log*

log ""
log "===== DONE ====="
