#!/bin/bash

if [ $# -lt 2 ]; then
  echo "Usage: $0 ID-FROM ID-TO" 2>/dev/null
  exit 1
fi

id1=$1
id2=$2

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

for id in $(seq $id1 $id2); do

  screen -S "normal-$id" -dm -t "normal-$id"
    screen -S "normal-$id" -p "normal-$id" -X stuff "$SCRIPT_DIR/run_repro \"nextflow-normal-${id}\"^M"

  screen -S "normal-$id" -dm -t "normal-$id"
    screen -S "normal-$id" -p "normal-$id" -X stuff "$SCRIPT_DIR/run_repro \"nextflow-base-${id}\" -b^M"

  screen -S "normal-$id" -dm -t "normal-$id"
    screen -S "normal-$id" -p "normal-$id" -X stuff "$SCRIPT_DIR/run_repro \"nextflow-blind-${id}\"^M"

  screen -S "normal-$id" -dm -t "normal-$id"
    screen -S "normal-$id" -p "normal-$id" -X stuff "$SCRIPT_DIR/run_repro \"nextflow-baseblind-${id}\" -b^M"


done
