#!/usr/bin/env bash

parentdir="$(dirname "$(pwd)")"

DRIVER_PATH="$parentdir/JQF/scripts/jqf-driver.sh"
JAR_PATH="$(pwd)/build/libs/growe-1.0-SNAPSHOT-all.jar"


function log() {
  echo "$1" | tee -a "$LOGFILE"
}

print_usage() {
  echo "Usage: $0 INPUT_PATH"
}

# Check arguments
if [ $# -lt 1 ]; then
  print_usage >&1
  exit 1
fi


export JVM_OPTS="$JVM_OPTS -Djqf.ei.MAX_INPUT_SIZE=204800"
export JVM_OPTS="$JVM_OPTS -Djqf.logCoverage=true"
export JVM_OPTS="$JVM_OPTS -Djqf.ei.QUIET_MODE=false"
export JVM_OPTS="$JVM_OPTS -Djqf.ei.GENERATE_EOF_WHEN_OUT=false"



#ei guidance
#export JVM_OPTS="$JVM_OPTS -Djqf.tracing.MATCH_CALLEE_NAMES=true -Djqf.tracing.TRACE_GENERATORS=true"

corpus="$(pwd)/$1/errorDir/corpus"
errordir="$(pwd)/$1/errorDir"
echo $errordir

reprodir="$(pwd)/$1/repro"
mkdir $reprodir
echo $reprodir
cd $reprodir

export JVM_OPTS="-Djqf.repro.traceDir=$errordir $JVM_OPTS"

export JVM_OPTS="$JVM_OPTS -Djqf.repro.logUniqueBranches=true -Xmx6g"

#export JVM_OPTS="$JVM_OPTS -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005"

/usr/bin/env bash -c "$DRIVER_PATH --illegal-access=permit -jar $JAR_PATH -g repro -r $corpus  | grep '^# Cov' | sort | uniq > ${errordir}/cov-all.log"


#export JVM_OPTS="$JVM_OPTS -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005"

export JVM_OPTS="$JVM_OPTS -Djqf.repro.ignoreInvalidCoverage=true"

/usr/bin/env bash -c "$DRIVER_PATH --illegal-access=permit -jar $JAR_PATH -g repro -r $corpus  | grep '^# Cov' | sort | uniq > ${errordir}/cov-valid.log"


