#!/usr/bin/env bash

parentdir="$(dirname "$(pwd)")"

DRIVER_PATH="$parentdir/JQF/scripts/jqf-driver.sh"
JAR_PATH="$(pwd)/build/libs/growe-1.0-SNAPSHOT-all.jar"

LOGFILE="./executor.log"

function log() {
  echo "$1" | tee -a "$LOGFILE"
}

DURATIONHOURS=2
DURATIONSECONDS=$((DURATIONHOURS * 60 * 60))
ITERATIONS=0 #max

EXEC_DIR="$(date +"%Y-%m-%d_%H-%M-%S")-${DURATIONHOURS}H"

basic="-b"
blind="TOTALLY_RANDOM=true"
if [[ $* == *"$basic"* ]]; then
  EXEC_DIR+="-basic"
fi
if [[ $JVM_OPTS == *"$blind"* ]]; then
  EXEC_DIR+="-blind"
fi

export JVM_OPTS="$JVM_OPTS -Djqf.ei.MAX_INPUT_SIZE=204800"
export JVM_OPTS="$JVM_OPTS -Djqf.logCoverage=true"
export JVM_OPTS="$JVM_OPTS -Djqf.ei.QUIET_MODE=false"
export JVM_OPTS="$JVM_OPTS -DuseFastNonCollidingCoverageInstrumentation=true"

# Do not let GC mess with fuzzing
export JVM_OPTS="$JVM_OPTS -XX:-UseGCOverheadLimit -Djqf.tracing.MATCH_CALLEE_NAMES=true"


#ei guidance
#export JVM_OPTS="$JVM_OPTS -Djqf.tracing.TRACE_GENERATORS=true"

#debug
export JVM_OPTS="$JVM_OPTS -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005"

function executeTest() {

  #core execution
  log ""
  log "===== Executing  ====="

  #-k -> keeptestfiles
  #-g -> guidance ei or zest
  #-b basic generator

  /usr/bin/env bash -c "$DRIVER_PATH --illegal-access=permit -Xmx4G -jar $JAR_PATH -d $DURATIONSECONDS -i $ITERATIONS $* | tee -a $LOGFILE 2>/dev/null"

}

# execution preparation
mkdir -p "$EXEC_DIR" || return 1
cd "$EXEC_DIR" || return 1

executeTest "$@"

rm -r work/
rm -r .nextflow/
rm .nextflow.log*

log ""
log "===== DONE ====="
