#!/bin/bash

if [ $# -lt 2 ]; then
  echo "Usage: $0 ID-FROM ID-TO" 2>/dev/null
  exit 1
fi

id1=$1
id2=$2
time=$((1*60*60))
timeouts=$((time + 30))

reprotime=$((1*20*60))
reprotimeouts=$((reprotime + 30))

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

for id in $(seq $id1 $id2); do

  echo "semantic-zest-$id timeout ${timeouts}s "
  screen -S "semantic-zest-$id" -dm -t "semantic-zest-$id"
  sleep 1
  screen -S "semantic-zest-$id" -p "semantic-zest-$id" -X stuff "timeout ${timeouts}s $SCRIPT_DIR/run_jqf \"semantic-zest\" $id ^M"

  echo "syntactic-zest-$id timeout ${timeouts}s"
  screen -S "syntactic-zest-$id" -dm -t "syntactic-zest-$id"
  sleep 1
  screen -S "syntactic-zest-$id" -p "syntactic-zest-$id" -X stuff "timeout ${timeouts}s $SCRIPT_DIR/run_jqf \"syntactic-zest\" $id -b ^M"

  echo "semantic-noguidance-$id timeout ${timeouts}s"
  screen -S "semantic-noguidance-$id" -dm -t "semantic-noguidance-$id"
  sleep 1
  screen -S "semantic-noguidance-$id" -p "semantic-noguidance-$id" -X stuff "timeout ${timeouts}s $SCRIPT_DIR/run_jqf \"semantic-noguidance\" $id ^M"

  echo "syntactic-noguidance-$id timeout ${timeouts}s"
  screen -S "syntactic-noguidance-$id" -dm -t "syntactic-noguidance-$id"
  sleep 1
  screen -S "syntactic-noguidance-$id" -p "syntactic-noguidance-$id" -X stuff "timeout ${timeouts}s $SCRIPT_DIR/run_jqf \"syntactic-noguidance\" $id -b ^M"

  sleep $timeouts

  echo "repro-semantic-zest-$id  timeout ${reprotimeouts}s"
  screen -S "repro-semantic-zest-$id" -dm -t "repro-semantic-zest-$id"
  sleep 1
  screen -S "repro-semantic-zest-$id" -p "repro-semantic-zest-$id" -X stuff "timeout ${reprotimeouts}s $SCRIPT_DIR/run_repro \"nextflow-semantic-zest-${id}\"^M"

  echo "repro-syntactic-zest-$id timeout ${reprotimeouts}s"
  screen -S "repro-syntactic-zest-$id" -dm -t "repro-syntactic-zest-$id"
  sleep 1
  screen -S "repro-syntactic-zest-$id" -p "repro-syntactic-zest-$id" -X stuff "timeout ${reprotimeouts}s $SCRIPT_DIR/run_repro \"nextflow-syntactic-zest-${id}\" -b^M"

  echo "repro-semantic-noguidance-$id timeout ${reprotimeouts}s"
  screen -S "repro-semantic-noguidance-$id" -dm -t "repro-semantic-noguidance-$id"
  sleep 1
  screen -S "repro-semantic-noguidance-$id" -p "repro-semantic-noguidance-$id" -X stuff "timeout ${reprotimeouts}s $SCRIPT_DIR/run_repro \"nextflow-semantic-noguidance-${id}\"^M"

  echo "repro-syntactic-noguidance-$id timeout ${reprotimeouts}s"
  screen -S "repro-syntactic-noguidance-$id" -dm -t "repro-syntactic-noguidance-$id"
  sleep 1
  screen -S "repro-syntactic-noguidance-$id" -p "repro-syntactic-noguidance-$id" -X stuff "timeout ${reprotimeouts}s $SCRIPT_DIR/run_repro \"nextflow-syntactic-noguidance-${id}\" -b^M"

  sleep $reprotimeouts

done
