#!/bin/bash

if [ $# -lt 2 ]; then
  echo "Usage: $0 ID-FROM ID-TO" 2>/dev/null
  exit 1
fi

id1=$1
id2=$2
time=$((2*60))

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

for id in $(seq $id1 $id2); do

  $SCRIPT_DIR/run_repro "nextflow-normal-${id}"
  #sleep $time #if running with screen
  sleep 10

  $SCRIPT_DIR/run_repro "nextflow-base-${id}" -b
  #sleep $time
  sleep 10

  $SCRIPT_DIR/run_repro "nextflow-blind-${id}"
  #sleep $time
  sleep 10

  $SCRIPT_DIR/run_repro "nextflow-baseblind-${id}" -b
  #sleep $time
  sleep 10

done
