<nextflow> ::= "#!/usr/bin/env nextflow" <nl> <processes> <workflow>
<nl> ::= "\n"

<processes> ::= <process>  |  <process>  <nl> <processes>
<magicstring> ::= "script1" | "script2.sh" | "script3" | "script4.txt" | "script5"

<process> ::= "process " <identifier> "{" <nl> "debug true" <nl> <input> <output> <script> <nl> "}" <nl>

<iotype> ::=  "val" |  "tuple"
<input> ::= "input:" <nl> <iotype>  " variable" <nl>
<output> ::= "output:" <nl> <iotype> " variable" <nl>

<script> ::= "script:" <nl> "template " <tick>  <magicstring> <tick>

<processcalls> ::= <identifier> <pipe> <identifier> | <identifier> <pipe> <processcalls>
<workflow> ::= " workflow " <workflowbody>
<workflowbody> ::= "{" <nl> <channel> <pipe> <processcalls> <nl> "}"

<channel> ::= "Channel.of" <open> <channellist> <close>
<channellist> ::= <channelitem> "," <channelitem> | <channelitem> "," <channellist>
<channelitem> ::= <uint> | '"' <identifier> '"'

<identifier> ::= a|b|c|d|e
<uint> ::= 1|2|3|4|5|6|7|8|9
<open> ::= "("
<close> ::= ")"
<pipe> ::= "|"
<tick> ::= "'"
