<nextflow> ::= "#!/usr/bin/env nextflow" <nl> <processes> <workflow>
<nl> ::= "\n"
<processes> ::= <process> <nl> <process> | <process> <nl> <processes>

<workflow> ::= "workflow " <workflowbody>
<process> ::= <process1> | <process2>
<process1> ::= "process " <identifier> " {" <nl> <processbody> <nl> "}" <nl>

<processbody> ::= "input: " <nl> "val variable " <nl> <nl> "output:" <nl> "val variable " <nl> <content>
<content> ::= <templatescript> | <script>
<templatescript> ::= "script: " <nl> " template 'scriptnamemagicstring'"
<quotes> ::= '"""'
<script> ::= "script: " <nl> <quotes> <nl> "scriptplaceholder1magicstring" <nl> <quotes>
<process2> ::= "process " <identifier2> "{" <nl> <processbody2> <nl> "}" <nl>

<processbody2> ::= "input:" <nl> "val variable" <nl> "val variable2 " <nl> <nl> "output:" <nl> "val variable" <nl> "val variable2" <nl> <content2>
<content2> ::= <templatescript2> | <script2>
<templatescript2> ::= "script:" <nl> "template 'scriptname2magicstring'"
<script2> ::= 'script:' <nl> <quotes> <nl> 'scriptplaceholder2magicstring' <nl> <quotes>

<workflowbody> ::= "{" <nl> <onevarchannel> <nl> <twovarchannel> <nl> "}"
<onevarchannel> ::= <channel> ".set{namedchannel1}" <nl> "namedchannel1 prozessscallmagicstring"
<twovarchannel> ::= <branchedchannel> ".set{namedchannel2}" <nl> "namedchannel2 prozesss2callmagicstring"
<channel> ::= "Channel.of" <open> <channellist> <close>
<branchedchannel> ::= <channel> ".multiMap { it -> one: two: it }"

<channellist> ::= <channelitem> "," <channelitem> | <channellist> "," <channelitem>
<channelitem> ::= <compchannelitem> | <uint> ".." <uint> | '"' <char> '".."' <char> '"'
<compchannelitem> ::= <number> | '"' <identifier> '"'

<identifier> ::= <char> | <char> <identifier>
<identifier2> ::= <identifier> "_twovars"
<char> ::= a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z
<uint> ::= 0|1|2|3|4|5|6|7|8|9
<number> ::= <uint> | <uint> <number>

<open> ::= "("
<close> ::= ")"
