<nextflow> ::= <shebang> <newline> <processes> <workflow>

<shebang> ::= "#!/usr/bin/env nextflow"
<magicstring> ::= "script1" | "script2.sh" | "script3" | "script4.txt" | "script5"

<processes> ::= <process> | <processes> <process>
<process> ::= <processheader> "{" <newline> <processbody> <newline> "}" <newline>

<processheader> ::= "process " <identifier>
<processbody> ::=  <input> <output> <script>
<input> ::= "input:" <newline> <inputvar> <newline>
<inputvar> ::= <iotype>  " variable" <newline>
<iotype> ::=  "val" |  "tuple"
<output> ::= "output:" <newline> <outputvar> <newline>
<outputvar> ::= <iotype> " variable" <newline>
<script> ::= "script:" <newline> "template '" <magicstring> "'"

<processcalls> ::= <identifier> " | " <identifier> | <identifier> " | " <processcalls>

<workflow> ::= " workflow " <workflowbody>
<channel> ::= "Channel.of" <open> <channellist> <close>
<channellist> ::= <channelitem> | <channellist> "," <channelitem>
<channelitem> ::= <uint> | '"' <identifier> '"'
<workflowbody> ::="{" <newline> <channel> " | " <processcalls> <newline> "}"

<identifier> ::= a|b|c|d|e
<uint> ::= 1|2|3|4|5|6|7|8|9
<open> ::= "("
<close> ::= ")"
<newline> ::= " \n "


