<nextflow> ::= "#!/usr/bin/env nextflow" <newline> <processes> <workflow>
<newline> ::= "\n"

<processes> ::= <process>  |  <process>  <newline> <processes>
<magicstring> ::= "script1" | "script2.sh" | "script3" | "script4.txt" | "script5"

<process> ::= "process " <identifier> "{" <newline> "debug true" <newline> <input> <output> <script> <newline> "}" <newline>

<iotype> ::=  "val" |  "tuple"
<input> ::= "input:" <newline> <iotype>  " variable" <newline>
<output> ::= "output:" <newline> <iotype> " variable" <newline>

<script> ::= "script:" <newline> "template " <tick>  <magicstring> <tick>

<processcalls> ::= <identifier> <pipe> <identifier> | <identifier> <pipe> <processcalls>
<workflow> ::= " workflow " <workflowbody>
<workflowbody> ::= "{" <newline> <channel> <pipe> <processcalls> <newline> "}"

<channel> ::= "Channel.of" <open> <channellist> <close>
<channellist> ::= <channelitem> "," <channelitem> | <channelitem> "," <channellist>
<channelitem> ::= <uint> | '"' <identifier> '"'

<identifier> ::= a|b|c|d|e
<uint> ::= 1|2|3|4|5|6|7|8|9
<open> ::= "("
<close> ::= ")"
<pipe> ::= "|"
<tick> ::= "'"
